### ISSUE TITLE
The package is not available on PyPI

### ISSUE THREAD

**Issue by buremba** [fishtown-analytics/dbt-presto#4]
`pip install dbt-presto` throws an exception because the package doesn't seem available on PyPI. See https://pypi.org/search/?q=dbt-presto

**Comment by drewbanin** [comment]
Hey @buremba - thanks for the heads up! We haven't been able to test `dbt-presto` in a production setting yet, so we've paused on releasing it on PyPi for the time being. My recommendation would be to clone the repo and install from source for the time being.

The README shows ` pip install dbt-presto` which is definitely not correct at the moment.... let me either
1) change these docs or
2) push the repo to pypi

at some point today. Thanks for the nudge :)

**Comment by buremba** [comment]
Thanks, @drewbanin. I have experience with Presto so let me know if there's anything that I can help with. I'm not sure about your plans so I didn't start looking into the codebase but for example, I'm pretty sure that we can make incremental models work in Presto. 

If you're looking for help for specific bugs/features, you may create issues. I'm watching the repo so I will get notifications and may issue a PR for some of those issues. It would also help me to learn more about DBT's codebase.

**Comment by drewbanin** [comment]
Ok, awesome! One of the challenges is that we don't have a good use case for Presto internally. With Redshift/Snowflake/BigQuery/SparkSQL, we're actively working on projects that inform the development of these plugins. For Presto, it's a little bit harder for us to prioritize features and fixes because we don't use this thing daily.

I think incremental models are a great place to start! Do you actually mind creating an issue? I'm super happy to point you in the right direction with contributing/understanding dbt's codebase/etc!

**Comment by drewbanin** [comment]
it's up on pypi now :) 

https://pypi.org/project/dbt-presto/
